import React, { useState, useEffect, useRef, useId } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowDown, ArrowRight, Play, Plus, Minus, X, Menu, Check, Copy, Download, Aperture, Sparkles, AudioLines, Layers, Clapperboard, } from 'lucide-react';
import '@fontsource-variable/manrope';
import '@fontsource-variable/dm-sans';
import '@fontsource/instrument-serif/400-italic.css';
import './styles.css';

const projects = [
  { id: 'open-road', title: 'The open road', type: 'Editing', tag: 'STORY & COLOR', image: '/images/desert-drive.webp', number: '01', description: 'A visual direction for a cinematic travel film. Warm, sun-faded tones, considered pacing, and a sense of possibility in every frame.', process: ['Build a story around the journey, not just the destination.', 'Shape the rhythm with intentional cuts and atmospheric sound.', 'Bring the desert to life with a warm, film-inspired grade.'], tools: 'DaVinci Resolve · Premiere Pro' },
  { id: 'otherworld', title: 'Beyond the ordinary', type: 'VFX', tag: 'COMPOSITING & VFX', image: '/images/otherworld.webp', number: '02', description: 'An otherworldly visual direction exploring scale, atmosphere, and the meeting point of practical storytelling and impossible worlds.', process: ['Develop a strong silhouette and an atmospheric visual language.', 'Explore procedural environments and effects in Houdini.', 'Integrate light, texture, and compositing into a cohesive frame.'], tools: 'SideFX Houdini · DaVinci Resolve' },
  { id: 'in-motion', title: 'Made to move', type: 'AI', tag: 'AI-ASSISTED CREATIVITY', image: '/images/in-motion.webp', number: '03', description: 'A fashion-inspired visual direction built around bold color and expressive movement. A starting point for blending human creative direction with AI-assisted production.', process: ['Define a distinctive mood, palette, and creative direction.', 'Explore AI-generated video and bespoke sound ideas.', 'Refine the final story through hands-on editing and sound design.'], tools: 'Gemini Omni · Suno · Premiere Pro' },
];
const services = [
  { name: 'Video editing & color', detail: 'From a collection of clips to a story worth watching. Thoughtful pacing, seamless transitions, color correction, and a cinematic finishing touch for films, branded content, and social media.', tags: 'DAVINCI RESOLVE / PREMIERE PRO / CAPCUT', icon: Clapperboard },
  { name: 'Compositing & visual effects', detail: 'When the idea goes beyond what a camera can capture. Procedural effects, atmospheric worlds, and compositing that supports the story — powered by SideFX Houdini.', tags: 'SIDEFX HOUDINI / COMPOSITING / VFX', icon: Layers },
  { name: 'AI-powered production', detail: 'A bigger creative playground. I explore AI video generation with Gemini Omni and original sound ideas with Lyria 3 and Suno, then bring the pieces together with an editor’s eye.', tags: 'GEMINI OMNI / LYRIA 3 / SUNO', icon: Sparkles },
  { name: 'Sound & storytelling', detail: 'Because a great edit is felt as much as it is seen. Dialogue, musical rhythm, sound design, and atmosphere come together to give every sequence its emotional shape.', tags: 'SOUND DESIGN / MUSIC EXPLORATION / NARRATIVE', icon: AudioLines },
];

function Modal({ children, onClose, title }) {
  const ref = useRef(null);
  const id = useId();
  useEffect(() => {
    const previous = document.activeElement;
    const oldOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    ref.current?.querySelector('button')?.focus();
    function onKey(e) {
      if (e.key === 'Escape') onClose();
      if (e.key === 'Tab') {
        const focusable = ref.current.querySelectorAll('button, a[href], input, select, textarea, [tabindex="0"]');
        const first = focusable[0], last = focusable[focusable.length - 1];
        if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); }
        else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
      }
    }
    document.addEventListener('keydown', onKey);
    return () => { document.body.style.overflow = oldOverflow; document.removeEventListener('keydown', onKey); previous?.focus(); };
  }, [onClose]);
  return <div className="modal-backdrop" onClick={e => e.target === e.currentTarget && onClose()}><div className="modal" role="dialog" aria-modal="true" aria-labelledby={id} ref={ref}><div className="modal-heading"><span id={id}>{title}</span><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={22}/></button></div>{children}</div></div>;
}

function BriefForm() {
  const [ready, setReady] = useState(false);
  const [copied, setCopied] = useState(false);
  const [brief, setBrief] = useState('');
  const [copyError, setCopyError] = useState(false);
  function submit(e) {
    e.preventDefault();
    const data = new FormData(e.target);
    setBrief(`PROJECT BRIEF FOR DIVINE\n\nName: ${data.get('name')}\nEmail: ${data.get('email')}\nService: ${data.get('service')}\nTimeline: ${data.get('timeline')}\n\nThe idea:\n${data.get('idea')}\n`);
    setReady(true);
  }
  function download() {
    const url = URL.createObjectURL(new Blob([brief], { type: 'text/plain' }));
    const a = document.createElement('a'); a.href = url; a.download = 'project-brief-for-divine.txt'; a.click(); URL.revokeObjectURL(url);
  }
  async function copy() {
    try { await navigator.clipboard.writeText(brief); setCopied(true); setCopyError(false); } catch { setCopyError(true); }
  }
  return ready ? <div className="brief-result"><div className="success-icon"><Check/></div><h2>A good story starts here.</h2><p>Your brief is ready. Save it and share it with Divine through your preferred contact channel. Nothing has been sent or stored.</p><pre>{brief}</pre><div className="button-row"><button className="button dark" onClick={download}>Download brief <Download size={17}/></button><button className="button outline" onClick={copy}>{copied ? 'Copied!' : 'Copy brief'} <Copy size={16}/></button></div>{copyError && <p role="alert">Clipboard access is unavailable. Please download your brief instead.</p>}<button className="text-button" onClick={() => setReady(false)}>Create another brief <ArrowRight size={15}/></button></div> : <form className="brief-form" onSubmit={submit}><div className="eyebrow red">LET’S MAKE SOMETHING GREAT</div><h2>Tell me about your idea.</h2><p>Turn your idea into a clear project brief. Download it, keep it, and share it when you’re ready.</p><div className="form-grid"><label>Your name<input name="name" placeholder="How should I call you?" required maxLength={100}/></label><label>Email address<input name="email" type="email" placeholder="you@example.com" required maxLength={150}/></label><label>What do you need?<select name="service"><option>Video editing & color</option><option>Compositing & VFX</option><option>AI-powered production</option><option>A little of everything</option></select></label><label>Your timeline<select name="timeline"><option>Let’s discuss</option><option>Within 2 weeks</option><option>This month</option><option>1–3 months</option></select></label></div><label>The big idea<textarea name="idea" rows={4} required maxLength={4000} placeholder="The story, the audience, the feeling. Tell me what you have in mind…"/></label><button className="button dark" type="submit">Create my brief <ArrowUpRight size={18}/></button><p className="form-note">This is a brief builder, not a submission form. Direct contact details will be added soon. Your information stays in your browser.</p></form>;
}

function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [filter, setFilter] = useState('All work');
  const [activeService, setActiveService] = useState(0);
  const [modal, setModal] = useState(null);
  const closeModal = React.useCallback(() => setModal(null), []);
  const visibleProjects = filter === 'All work' ? projects : projects.filter(p => p.type === filter);
  return <>
    <a href="#main-content" className="skip-link">Skip to content</a>
    <header className="site-header wrap"><a className="logo" href="#home" aria-label="Divine home">divine<span>®</span></a><nav className={menuOpen ? 'navigation is-open' : 'navigation'} aria-label="Main navigation">{[['Work', 'work'], ['Expertise', 'expertise'], ['About', 'about']].map(([text, id]) => <a key={id} href={`#${id}`} onClick={() => setMenuOpen(false)}>{text}</a>)}<a className="nav-contact" href="#contact" onClick={() => setMenuOpen(false)}>Let’s talk <ArrowUpRight size={16}/></a></nav><button className="mobile-menu icon-button" aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X/> : <Menu/>}</button></header>
    <main id="main-content">
      <section className="hero wrap" id="home">
        <div className="hero-copy"><div className="eyebrow"><span className="status-dot"/> VIDEO EDITOR & VISUAL STORYTELLER</div><h1>Good footage.<br/>Great stories.<br/><span>A little <i>Divine.</i></span><svg className="title-spark" viewBox="0 0 70 70" aria-hidden="true"><path d="M35 2v66M2 35h66M12 12l46 46M12 58l46-46"/></svg></h1><p>I turn ideas into visuals that make you feel something.<br className="desktop-break"/> Editing, VFX, and a little AI magic — all in service<br className="desktop-break"/> of a story worth telling.</p><div className="hero-actions"><a className="button dark" href="#work">Explore my work <ArrowUpRight size={18}/></a><button className="process-link" onClick={() => setModal('process')}><span className="play-circle"><Play size={12} fill="currentColor"/></span> Behind the process</button></div><div className="hero-location"><span className="small-star">✳</span> BASED IN AWKA, NIGERIA <span className="location-divider"/> CREATING EVERYWHERE</div></div>
        <div className="hero-visual"><img src="/images/desert-drive.webp" alt="Cinematic concept of an orange sports car on a winding desert road" fetchPriority="high"/><div className="visual-top"><span><i/> THE ART OF THE EDIT</span><Aperture size={21}/></div><div className="frame-corner top-left"/><div className="frame-corner bottom-right"/><div className="visual-bottom"><div><span className="eyebrow">EVERY FRAME, INTENTIONAL.</span><p>Not just seen.<br/><em>Felt.</em></p></div><button aria-label="Explore The open road concept" className="visual-arrow" onClick={() => setModal(projects[0])}><ArrowUpRight size={24}/></button></div><span className="image-disclosure">AI-GENERATED CONCEPT FRAME</span></div>
      </section>
      <section className="toolkit wrap" aria-label="Creative software"><span className="toolkit-label">THE TOOLS CHANGE.<br/><strong>THE VISION DOESN’T.</strong></span><div className="tool-brand resolve"><Aperture/><span>DaVinci Resolve</span></div><div className="tool-brand premiere"><span className="app-icon">Pr</span><span>Premiere Pro</span></div><div className="tool-brand houdini"><span className="houdini-mark">◉</span><span>Houdini</span></div><div className="tool-brand capcut"><span className="capcut-mark">⋈</span><span>CapCut</span></div><div className="tool-brand ai-brand"><Sparkles/><span>AI, in the mix.</span></div></section>
      <section className="work-section wrap section-space" id="work"><div className="section-topline"><span className="eyebrow"><span className="red small-plus">+</span> THE CREATIVE RANGE</span><span className="section-index">01 / SELECTED DIRECTIONS</span></div><div className="section-heading"><h2>Different worlds.<br/>Same <span className="serif">attention to detail.</span></h2><p>From the first cut to the final feeling.<br/>A look at the worlds I love to create.</p></div><div className="work-controls"><div className="filters" aria-label="Filter creative directions">{['All work', 'Editing', 'VFX', 'AI'].map(item => <button key={item} onClick={() => setFilter(item)} aria-pressed={filter === item} className={filter === item ? 'active' : ''}>{item}{item === 'All work' && <span>03</span>}</button>)}</div><span className="concept-note">Concept gallery · Original projects coming soon</span></div><div className={`project-grid ${visibleProjects.length === 1 ? 'filtered' : ''}`}>{visibleProjects.map(p => <button className="project-card" key={p.id} onClick={() => setModal(p)}><div className="project-image"><img src={p.image} alt={p.title === 'The open road' ? 'Golden desert road with an orange car' : p.type === 'VFX' ? 'Glowing celestial ring above dark water' : 'Fashion portrait with sculptural orange fabric'} loading="lazy"/><span className="project-number">{p.number} /</span><span className="project-open"><ArrowUpRight size={21}/></span><span className="concept-badge">CONCEPT FRAME</span></div><div className="project-info"><div><span className="eyebrow">{p.tag}</span><h3>{p.title}</h3></div><ArrowUpRight size={20}/></div></button>)}</div><div className="work-footnote"><span>AI-generated imagery above illustrates creative directions, not completed client work.</span><span>A STORY-FIRST APPROACH <ArrowDown size={13}/></span></div></section>
      <section className="expertise-section" id="expertise"><div className="wrap expertise-layout"><div className="expertise-intro"><div className="eyebrow"><span className="red small-plus">+</span> WHAT I BRING TO THE TIMELINE</div><h2>One creative.<br/><span className="serif">Many possibilities.</span></h2><p>The right tool for the right story. I move between traditional editing, complex effects, and emerging AI tools to bring your vision to life.</p><a className="text-link" href="#contact">Let’s find your direction <ArrowUpRight size={18}/></a><div className="timeline-art" aria-hidden="true"><div className="timeline-head"><span>SEQUENCE 01</span><span>00:00:03:00</span></div><div className="timeline-track"><span>V3</span><i/><i/></div><div className="timeline-track"><span>V2</span><i/><i/><i/></div><div className="timeline-track"><span>A1</span><div className="waveform">▂▅▃▇▄▂▆▇▂▄▅▇▄▂▆▂▄▇▅▃▆▅▂▃▆▇▄▅</div></div><div className="playhead"/></div></div><div className="services">{services.map((s, i) => <div className={`service ${activeService === i ? 'expanded' : ''}`} key={s.name}><button onClick={() => setActiveService(activeService === i ? null : i)} aria-expanded={activeService === i} aria-controls={`service-${i}`}><span className="service-number">0{i + 1}</span><span>{s.name}</span>{activeService === i ? <Minus size={19}/> : <Plus size={19}/>}</button><div id={`service-${i}`} className="service-content" hidden={activeService !== i}><p>{s.detail}</p><div className="service-tags">{s.tags}</div></div></div>)}</div></div></section>
      <section className="about-section wrap section-space" id="about"><div className="about-portrait"><div className="portrait-top"><span>THE PERSON BEHIND THE PIXELS</span><ArrowUpRight size={19}/></div><div className="portrait-monogram" aria-hidden="true">d<span>.</span><svg viewBox="0 0 70 70"><path d="M35 2v66M2 35h66M12 12l46 46M12 58l46-46"/></svg></div><div className="portrait-bottom"><span>DIVINE CHUKWUDEBELU<br/>UGOCHUKWU</span><span className="portrait-pending">Portrait coming soon</span></div></div><div className="about-copy"><div className="eyebrow"><span className="red small-plus">+</span> A LITTLE ABOUT ME</div><h2>An editor’s eye.<br/>A storyteller’s <span className="serif">heart.</span></h2><p>I’m Divine Chukwudebelu Ugochukwu — a video editor, visual explorer, and Theatre Arts student at UNIZIK in Awka, Nigeria.</p><p>For about three years, I’ve been turning footage into stories. My background in theatre shapes the way I edit: with an instinct for rhythm, emotion, and the moments that matter.</p><p>Whether I’m building an effect in Houdini, finding the perfect cut in Resolve, or experimenting with AI, the goal is always the same: make something that stays with you.</p><div className="about-stats"><div><strong><span>~</span>3</strong><span>YEARS OF EXPLORING</span></div><div><strong>∞</strong><span>WAYS TO TELL A STORY</span></div><div><span className="stat-location">AWKA, NG <ArrowUpRight size={15}/></span><span>ROOTED HERE. THINKING BIG.</span></div></div></div></section>
      <section className="contact-section wrap" id="contact"><div className="contact-panel"><div className="contact-top"><span className="eyebrow"><span className="status-dot"/> OPEN TO CREATIVE COLLABORATIONS</span><span>YOUR NEXT CHAPTER STARTS HERE ↙</span></div><div className="contact-main"><h2>Have a story?<br/>Let’s make it <span className="serif">move.</span></h2><button className="contact-circle" aria-label="Start a project brief" onClick={() => setModal('contact')}><ArrowUpRight size={46}/></button></div><div className="contact-bottom"><p>A film. A campaign. An idea you can’t stop thinking about.<br/>Let’s see where we can take it.</p><button className="text-link" onClick={() => setModal('contact')}>Start a project brief <ArrowUpRight size={19}/></button></div></div></section>
    </main><footer className="footer wrap"><a href="#home" className="logo">divine<span>®</span></a><span>Thoughtfully cut. Intentionally created.</span><div>© {new Date().getFullYear()} Divine Ugochukwu <a href="#home" aria-label="Back to top"><ArrowUpRight size={18}/></a></div></footer>
    {modal && <Modal onClose={closeModal} title={modal === 'contact' ? 'A NEW COLLABORATION' : modal === 'process' ? 'BEHIND THE PROCESS' : 'CREATIVE DIRECTION / ' + modal.number}>{modal === 'contact' ? <BriefForm/> : modal === 'process' ? <div className="process-modal"><div className="eyebrow red">STORY FIRST. ALWAYS.</div><h2>More than a sequence of cuts.</h2><p>Every project starts with a feeling. Here’s how I find it.</p>{[['Listen & discover', 'The audience. The intention. The emotion. Before opening a timeline, I get clear on what the story needs to say.'], ['Explore & assemble', 'I find the strongest moments, build a narrative, and choose the tools that bring the idea to life — not the other way around.'], ['Refine & finish', 'Pacing, color, sound, and the little details. I keep refining until the final frame feels as considered as the first.']].map(([title, body], i) => <div className="process-step" key={title}><span>0{i + 1}</span><div><h3>{title}</h3><p>{body}</p></div></div>)}<div className="modal-note">Showreel coming soon. In the meantime, explore the concept gallery to get a feel for my creative interests.</div></div> : <div className="project-modal"><img src={modal.image} alt={`${modal.title} — AI-generated concept artwork`}/><div className="project-modal-copy"><div className="eyebrow red">{modal.tag} / CONCEPT STUDY</div><h2>{modal.title}</h2><p>{modal.description}</p><h3>The approach</h3><ol>{modal.process.map(s => <li key={s}>{s}</li>)}</ol><div className="project-tools">A possible toolkit <strong>{modal.tools}</strong></div><div className="modal-note">This AI-generated still is a visual concept, not a completed project or a playable video. Original video work will be added here when available.</div></div></div>}</Modal>}
  </>;
}

createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
